version: "2.2"

services:
  postgres-comexStockInventory:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sas
      - POSTGRES_USER=sas
      - POSTGRES_DB=sas
    volumes:
      - postgres-data:/var/lib/postgresql/sas

volumes:
  postgres-data:
    driver: local
